spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        use_sql_comments: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false

#logging:
#  level: 
#    root: debug
