version: "3.5"

services:
  joke-service:
    image: afrunt/joke-service
    ports:
      - 8080:8080
      - 9090:9090
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - APM_ENABLED=true
      - APM_SERVER_URLS=http://apm:8200
      - MEM_MAX=256m
      - BULK_MAX_SIZE=1000
      - DB_MAX_POOL_SIZE=50
        
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker-compose/data/postgres:/var/lib/postgresql/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker-compose/data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:6.8.0
    ports:
      - 8200:8200
    environment:
      - 'output.elasticsearch.hosts=["elasticsearch:9200"]'
    depends_on:
      - elasticsearch
      - kibana
    restart: on-failure
    volumes:
      - ./docker-compose/config/apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
      
