version: "3.5"

services:
  joke-service:
    image: afrunt/joke-service
    
  postgress:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:6.8.0
    ports:
      - 8200:8200
    environment:
      - 'output.elasticsearch.hosts=["elasticsearch:9200"]'
    depends_on:
      - elasticsearch
      - kibana
    restart: on-failure
    volumes:
      - ./config/apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
      
