jokeservice:
  url: http://localhost:8080
crawler:
  jobs:
    randomjokecrawler:
      batchSize: 100000
      bufferSize: 10000
  
spring:
  datasource:
    url: jdbc:h2:./jokedb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    data-username: sa
    data-password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        generate_statistics: false
        use_sql_comments: false
        format_sql: true
    show-sql: false
